### ISSUE TITLE
The game is crashing on startup

### ISSUE THREAD

**Issue by nikitosoz8** [JozielBorges/phasmophobia-discord-rich-presence#1]
So every time I try to open the game, it allows me in for like a few seconds and after just crash.

**Comment by KnucklesB** [comment]
Hello sir, sorry for the super late reply...

after a update the game devs add a way to detect the melon loader class in the game class, making the game crash...

you may wants to check this project: [[phasmopresence](https://github.com/manucabral/phasmopresence)](https://github.com/manucabral/phasmopresence)
