### ISSUE TITLE
Continuation

### ISSUE THREAD

**Issue by RobinRMC** [JozielBorges/phasmophobia-discord-rich-presence#2]
Do you have any plans to make this work again or make a new version? Maybe without MelonLoader?

**Comment by ne0de** [comment]
> Do you have any plans to make this work again or make a new version? Maybe without MelonLoader?

maybe you be interested on [phasmopresence](https://github.com/manucabral/phasmopresence)

**Comment by RobinRMC** [comment]
> > Do you have any plans to make this work again or make a new version? Maybe without MelonLoader?
> 
> maybe you be interested on [phasmopresence](https://github.com/manucabral/phasmopresence)

Thanks for helping! 😃
