### ISSUE TITLE
Does this project break Phasmophobia TOS?

### ISSUE THREAD

**Issue by lambdakilo** [JozielBorges/phasmophobia-discord-rich-presence#3]

**Comment by onyxdev25** [comment]
@akirataguchi115 Yep, nothing here that is breaking Phasmophobia TOS or pretty much any popular game's TOS.

**Comment by lambdakilo** [comment]
Isn't melon loader a mod? The EULA can be found Phasmophobia\Phasmophobia EULA (Ver 2).pdf
![image](https://user-images.githubusercontent.com/31825085/223769529-b779b8b9-e206-4439-8f1d-942b960ec137.png)

**Comment by KnucklesB** [comment]
The project don't break the game TOS, but melon loader does, melon loader is a custom script loader, phasmo don't allows it because can be used for bad stuffs as cheating.
sorry for the late reply, i was busy :(
